<a href="https://colab.research.google.com/github/AnindyaNaura12/Data-Mining/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [6]:
df = pd.read_csv('diabetes.csv')
print(df.shape)
df.describe().transpose()

(768, 9)

,count,mean,std,min,25%,50%,75%,max
Pregnancies,768.0,3.845052,3.369578,0.000,1.00000,3.0000,6.00000,17.00
Glucose,768.0,120.894531,31.972618,0.000,99.00000,117.0000,140.25000,199.00
BloodPressure,768.0,69.105469,19.355807,0.000,62.00000,72.0000,80.00000,122.00
SkinThickness,768.0,20.536458,15.952218,0.000,0.00000,23.0000,32.00000,99.00
Insulin,768.0,79.799479,115.244002,0.000,0.00000,30.5000,127.25000,846.00
BMI,768.0,31.992578,7.884160,0.000,27.30000,32.0000,36.60000,67.10
DiabetesPedigreeFunction,768.0,0.471876,0.331329,0.078,0.24375,0.3725,0.62625,2.42
Age,768.0,33.240885,11.760232,21.000,24.00000,29.0000,41.00000,81.00
Outcome,768.0,0.348958,0.476951,0.000,0.00000,0.0000,1.00000,1.00

In [7]:
target_column = ['Outcome']
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Pregnancies,768.0,0.226180,0.198210,0.000000,0.058824,0.176471,0.352941,1.0
Glucose,768.0,0.607510,0.160666,0.000000,0.497487,0.587940,0.704774,1.0
BloodPressure,768.0,0.566438,0.158654,0.000000,0.508197,0.590164,0.655738,1.0
SkinThickness,768.0,0.207439,0.161134,0.000000,0.000000,0.232323,0.323232,1.0
Insulin,768.0,0.094326,0.136222,0.000000,0.000000,0.036052,0.150414,1.0
BMI,768.0,0.476790,0.117499,0.000000,0.406855,0.476900,0.545455,1.0
DiabetesPedigreeFunction,768.0,0.194990,0.136913,0.032231,0.100723,0.153926,0.258781,1.0
Age,768.0,0.410381,0.145188,0.259259,0.296296,0.358025,0.506173,1.0
Outcome,768.0,0.348958,0.476951,0.000000,0.000000,0.000000,1.000000,1.0

In [8]:
X = df [predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(537, 8)
(231, 8)

In [12]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

hidden_layers = [
    (10,10,6),
    (6,8,9),
    (6,9,1),
    (6,3,9),
    (7,10,8)
]

In [13]:
hasil = []

In [14]:
for hl in hidden_layers:

    mlp = MLPClassifier(
        hidden_layer_sizes=hl,
        activation='relu',
        solver='adam',
        max_iter=500,
        random_state=40
    )

    mlp.fit(X_train, y_train.ravel())

    y_pred = mlp.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    hasil.append([hl, acc])

    print(f"\nHidden Layer: {hl}")
    print(f"Accuracy: {acc:.4f}")
    print(classification_report(y_test, y_pred))

Hidden Layer: (10, 10, 6)
Accuracy: 0.7489
              precision    recall  f1-score   support

           0       0.75      0.89      0.81       142
           1       0.75      0.52      0.61        89

    accuracy                           0.75       231
   macro avg       0.75      0.71      0.71       231
weighted avg       0.75      0.75      0.74       231


Hidden Layer: (6, 8, 9)
Accuracy: 0.7489
              precision    recall  f1-score   support

           0       0.76      0.87      0.81       142
           1       0.72      0.56      0.63        89

    accuracy                           0.75       231
   macro avg       0.74      0.71      0.72       231
weighted avg       0.75      0.75      0.74       231


Hidden Layer: (6, 9, 1)
Accuracy: 0.6147
              precision    recall  f1-score   support

           0       0.61      1.00      0.76       142
           1       0.00      0.00      0.00        89

    accuracy                           0.61       231
   macro avg       0.31      0.50      0.38       231
weighted avg       0.38      0.61      0.47       231

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Hidden Layer: (6, 3, 9)
Accuracy: 0.7446
              precision    recall  f1-score   support

           0       0.76      0.86      0.81       142
           1       0.71      0.56      0.63        89

    accuracy                           0.74       231
   macro avg       0.74      0.71      0.72       231
weighted avg       0.74      0.74      0.74       231


Hidden Layer: (7, 10, 8)
Accuracy: 0.7489
              precision    recall  f1-score   support

           0       0.76      0.87      0.81       142
           1       0.73      0.55      0.63        89

    accuracy                           0.75       231
   macro avg       0.74      0.71      0.72       231
weighted avg       0.75      0.75      0.74       231

In [15]:
print("\n===== RINGKASAN HASIL =====")

for hl, acc in hasil:
    print(f"{hl} --> {acc:.4f}")

===== RINGKASAN HASIL =====
(10, 10, 6) --> 0.7489
(6, 8, 9) --> 0.7489
(6, 9, 1) --> 0.6147
(6, 3, 9) --> 0.7446
(7, 10, 8) --> 0.7489

In [18]:
# Target di kolom terakhir
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [19]:
# ====== PREPROCESSING ======
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [20]:
# ====== ACTIVATION LIST ======
activations = ['logistic', 'tanh', 'relu', 'identity']

results = []

for act in activations:
    model = MLPClassifier(
        hidden_layer_sizes=(10, 10, 6),
        activation=act,
        max_iter=1000,
        random_state=42
    )

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    results.append((act, acc))

    print(f"\n=== Activation: {act} ===")
    print("Accuracy:", acc)
    print(classification_report(y_test, y_pred))

=== Activation: logistic ===
Accuracy: 0.7337662337662337
              precision    recall  f1-score   support

           0       0.82      0.76      0.79        99
           1       0.61      0.69      0.65        55

    accuracy                           0.73       154
   macro avg       0.71      0.72      0.72       154
weighted avg       0.74      0.73      0.74       154


=== Activation: tanh ===
Accuracy: 0.7597402597402597
              precision    recall  f1-score   support

           0       0.81      0.82      0.81        99
           1       0.67      0.65      0.66        55

    accuracy                           0.76       154
   macro avg       0.74      0.74      0.74       154
weighted avg       0.76      0.76      0.76       154


=== Activation: relu ===
Accuracy: 0.7012987012987013
              precision    recall  f1-score   support

           0       0.78      0.75      0.76        99
           1       0.58      0.62      0.60        55

    accuracy                           0.70       154
   macro avg       0.68      0.68      0.68       154
weighted avg       0.71      0.70      0.70       154


=== Activation: identity ===
Accuracy: 0.7402597402597403
              precision    recall  f1-score   support

           0       0.81      0.78      0.79        99
           1       0.63      0.67      0.65        55

    accuracy                           0.74       154
   macro avg       0.72      0.73      0.72       154
weighted avg       0.75      0.74      0.74       154

In [21]:
# ====== SUMMARY ======
print("\n=== RINGKASAN HASIL ===")
for r in results:
    print(f"{r[0]} -> Accuracy: {r[1]:.4f}")

=== RINGKASAN HASIL ===
logistic -> Accuracy: 0.7338
tanh -> Accuracy: 0.7597
relu -> Accuracy: 0.7013
identity -> Accuracy: 0.7403

In [9]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1124: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[321  37]
 [ 78 101]]
              precision    recall  f1-score   support

           0       0.80      0.90      0.85       358
           1       0.73      0.56      0.64       179

    accuracy                           0.79       537
   macro avg       0.77      0.73      0.74       537
weighted avg       0.78      0.79      0.78       537

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
df = pd.read_csv('diabetes.csv')

target_column = ['Outcome']
predictors = list(set(df.columns) - set(target_column))

In [ ]:
# Normalisasi
df[predictors] = df[predictors] / df[predictors].max()

X = df[predictors].values
y = df[target_column].values.ravel()

In [ ]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=40
)

In [ ]:
# Hidden layer variations
layers_list = [
    (10,10,6),
    (6,8,9),
    (6,9,1),
    (6,3,9),
    (7,10,8)
]

results = []

In [ ]:
for layers in layers_list:
    mlp = MLPClassifier(hidden_layer_sizes=layers,
                        activation='relu',
                        solver='adam',
                        max_iter=500,
                        random_state=40)

In [ ]:
mlp.fit(X_train, y_train)

In [ ]:
pred = mlp.predict(X_test)
acc = accuracy_score(y_test, pred)

In [ ]:
print("\nHidden Layers:", layers)
print("Accuracy:", acc)
print(classification_report(y_test, pred))

results.append((layers, acc))

In [ ]:
# ranking hasil
results.sort(key=lambda x: x[1], reverse=True)

print("\n=== BEST MODEL ===")
print(results[0])

In [ ]:
# Percobaan 2
import numpy as np
from sklearn. datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Load dataset Iris
iris = load_iris()
X = iris.data
y = iris.target

In [ ]:
# Bagi data menjadi data pelatihan dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Standarisasi fitur
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Inisialisasi dan pelatihan model MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(2,), max_iter=5000, alpha=0.01, solver='adam', random_state=42)
mlp.fit(X_train, y_train)

In [ ]:
# Prediksi pada data uji
y_pred = mlp.predict(X_test)

In [ ]:
# Evaluasi model
accuracy = accuracy_score(y_test, y_pred)
print(f'Akurasi: {accuracy * 100}%')
print(classification_report(y_test, y_pred, target_names=iris.target_names))

In [ ]:
# Menampilkan arsitektur jaringan syaraf
print("\nArsitektur Neural Network:")
print(f"Input Layer: {X_train. shape[1]} neurons")
for i, size in enumerate(mlp.hidden_layer_sizes):
  print(f"Hidden Layer {i + 1}: {size} neurons")
print(f"Output Layer: {mlp.n_outputs_} neurons")
print(f"Fungsi Aktivasi: {mlp.activation}")

In [ ]:
# Jika ingin melihat bobot dan bias hasil pelatihan
print("\nBobot dan Bias:")
print("Bobot antara input dan hidden layer:")
print(mlp.coefs_[0])
print("Bobot antara hidden dan output layer:")
print(mlp.coefs_[1])
print("Biase dari hidden layer:")
print(mlp.intercepts_[0])
print("Bias dari output layer:")
print(mlp.intercepts_[1])

In [ ]:
# Percobaan 3
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

In [ ]:
# Load dataset Iris
iris = load_iris()
X = iris.data
y = iris.target

In [ ]:
# One-hot encoding untuk label
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y.reshape(-1, 1))

In [ ]:
# Bagi data menjadi data pelatihan dan data uji
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=0.2, random_state=42)

In [ ]:
# Fungsi aktivasi sigmoid
def sigmoid(x):
  return 1 / (1 + np.exp (-x))

In [ ]:
# Turunan fungsi sigmoid
def sigmoid_derivative(x):
  return x * (1 - x)

In [ ]:
# Parameter jaringan neural
input_layer_neurons = X_train.shape[1]
hidden_layer_neurons = 10
output_layer_neurons = y_train.shape[1]

In [ ]:
# Inisialisasi bobot dan bias
np.random.seed(42)

weights_input_hidden = np.random.uniform(
    size=(input_layer_neurons, hidden_layer_neurons)
)

weights_hidden_output = np.random.uniform(
    size=(hidden_layer_neurons, output_layer_neurons)
)

bias_hidden = np.random.uniform(
    size=(1, hidden_layer_neurons)
)

bias_output = np.random.uniform(
    size=(1, output_layer_neurons)
)

In [ ]:
# Hiperparameter
learning_rate = 0.01
epochs = 5000

In [ ]:
# Proses pelatihan
for epoch in range(epochs):
  # Forward propagation
  hidden_layer_input = np.dot(X_train, weights_input_hidden) + bias_hidden
  hidden_layer_output = sigmoid(hidden_layer_input)

  output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
  predicted_output = sigmoid(output_layer_input)

In [ ]:
# Backpropagation
error = y_train - predicted_output

d_predicted_output = error * sigmoid_derivative(predicted_output)

error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

In [ ]:
# Update bobot dan bias
weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate

weights_input_hidden += X_train.T.dot(d_hidden_layer) * learning_rate
bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

In [ ]:
for epoch in range(epochs):

    # forward
    hidden_layer_input = np.dot(X_train, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_input)

    # error
    error = y_train - predicted_output

    # backprop
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # update
    weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate

    weights_input_hidden += X_train.T.dot(d_hidden_layer) * learning_rate
    bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    # print loss tiap 1000 epoch
    if (epoch + 1) % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch + 1}, Loss: {loss}")

Epoch 1000, Loss: 0.0196573153636917
Epoch 2000, Loss: 0.013122324792401649
Epoch 3000, Loss: 0.012098474100176055
Epoch 4000, Loss: 0.011671424181885716
Epoch 5000, Loss: 0.011416837921159035

In [ ]:
# Prediksi pada data uji
hidden_layer_input = np.dot(X_test, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
predicted_output = sigmoid(output_layer_input)

In [ ]:
# Evaluasi Model
y_test_labels = np.argmax(y_test, axis=1)
predicted_labels = np.argmax(predicted_output, axis=1)

accuracy = accuracy_score(y_test_labels, predicted_labels)

print(f"Accuracy: {accuracy * 100}%")

Accuracy: 96.66666666666667%